version: '3'
 
services:

    php:
        build:
            context: ./docker/php
        volumes:
            - ./app:/app
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        depends_on:
          - mysql
 
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./app:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        image: mysql:latest
        command: '--default-authentication-plugin=mysql_native_password'
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./db-data:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
          PMA_HOST: mysql
          PMA_USER: root
          PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - 8080:80
        depends_on:
          - mysql
